apiVersion: v1
kind: Service
metadata:
  name: {{ include "opengist.fullname" . }}
  labels:
    {{- include "opengist.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ssh.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "opengist.selectorLabels" . | nindent 4 }}
